[target.aarch64-linux-android]
linker = "/run/media/ACLaniakea/IXUNICS/pad/coloros-pad-fixes/workspace/toolchains/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-feature=+crt-static"]
