[MON-BATTERY-STANDBY]
algo_type        monitor
sensor           pm8550b-chg-therm
sampling         1000
thresholds       40000          43000      43800
thresholds_clr   38000          40000      43000
actions          battery       battery    battery
action_info      3               6          7
action_info      3               6         7

[MON-BATTERY-USER]
algo_type        monitor
sensor           skin-msm-therm-usr
sampling         1000
thresholds       36000      40000      44000      48000
thresholds_clr   34000      36000      40000      44000
actions          battery       battery    battery   battery
action_info      11               17          17         21

[THERM_CLUSTER-1_0]
algo_type        ss
sensor           skin-msm-therm-usr
sampling         1000
device           cpu-cluster0
set_point        38000
set_point_clr    36000
device_max_limit 2035200
